### ISSUE TITLE
500 Server Error, Unable to Connect to DB

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee-v3#172]
### Detailed description of the problem
Unable to submit my settings in the UI to use my existing db from my previous electerious installation.

![palemoon_2019-01-15_08-29-39](https://user-images.githubusercontent.com/5841249/51184750-38037f80-18a3-11e9-915d-be60aab705f5.png)

When I copy my old config, I only receive the "Server error or API not found" error at the top of the page.

![palemoon_2019-01-15_08-58-28](https://user-images.githubusercontent.com/5841249/51184964-d7287700-18a3-11e9-8c14-518f1f9c6fe5.png)

I'm not seeing anything under F12>Network>Response nor Preview.
![palemoon_2019-01-15_08-58-43](https://user-images.githubusercontent.com/5841249/51185073-2f5f7900-18a4-11e9-8545-6f03a8d9f1f2.png)
![palemoon_2019-01-15_08-58-51](https://user-images.githubusercontent.com/5841249/51185078-3090a600-18a4-11e9-8305-8139f57d01b9.png)

### Steps to reproduce the issue

I've reinstalled using the new LycheeOrg release, and tried copying my database, uploads, and config over from my previous electerious installation. (The old one doesn't work right now either, notably.)

I don't seem to have any leftover php5 packages as was causing a similar user's issue. (I shouldn't have had any in the first place, as this is a fresh Debian 9 installation.) I'm also finding my database & tables successfully. My webserver seems to be operating fine in other instances I currently have hosted. I'm lost as to what may be the cause.

I've tried this both with my linked dir and using a local one to the same result.
```
harley@olympic /m/i/b/w/i/Lychee ❯❯❯ ls -l
total 240
drwxrwxr-x 1 harley users    20 Jan 15 08:24 data
drwxr-xr-x 1 harley users    70 Jan 15 08:24 dist
drwxr-xr-x 1 harley users   332 Jan 15 08:24 docs
drwxr-xr-x 1 harley users   258 Jan 15 08:24 Lychee-front
drwxr-xr-x 1 harley users   136 Jan 15 08:24 php
drwxr-xr-x 1 harley users    28 Jan 15 08:24 plugins
lrwxrwxrwx 1 harley users    52 Jan 15 08:13 uploads -> /media/ivanka/backupLinux/lycheeIncorrigible/uploads
drwxr-xr-x 1 harley users   156 Jan 15 08:33 vendor
-rw-r--r-- 1 harley users  3219 Jan 15 08:24 CODE_OF_CONDUCT.md
-rw-r--r-- 1 harley users    70 Jan 15 08:24 composer.json
-rw-r--r-- 1 harley users 21593 Jan 15 08:24 composer.lock
-rw-r--r-- 1 harley users 33412 Jan 15 08:24 favicon.ico
-rw-r--r-- 1 harley users 67985 Jan 15 08:24 index.html
-rw-r--r-- 1 harley users  1084 Jan 15 08:24 LICENSE
-rw-r--r-- 1 harley users  2300 Jan 15 08:24 makefile
-rw-r--r-- 1 harley users 23586 Jan 15 08:24 README.md
-rw-r--r-- 1 harley users   216 Jan 15 08:24 robots.txt
-rw-r--r-- 1 harley users     6 Jan 15 08:24 version.md
-rw-r--r-- 1 harley users 65386 Jan 15 08:24 view.php
harley@olympic /m/i/b/w/i/Lychee ❯❯❯
```

Reinstalled
```
harley@olympic /m/i/b/w/i/Lychee ❯❯❯ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing monolog/monolog (1.24.0)
    Loading from cache

  - Installing symfony/polyfill-ctype (v1.10.0)
    Loading from cache

  - Installing symfony/filesystem (v3.4.18)
    Loading from cache

  - Installing neutron/temporary-filesystem (2.3.0)
    Loading from cache

  - Installing evenement/evenement (v2.1.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.2)
    Loading from cache

  - Installing symfony/process (v3.4.18)
    Loading from cache

  - Installing alchemy/binary-driver (v2.0.0)
    Loading from cache

  - Installing php-ffmpeg/php-ffmpeg (v0.13)
    Loading from cache

monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
php-ffmpeg/php-ffmpeg suggests installing php-ffmpeg/extras (A compilation of common audio & video drivers for PHP-FFMpeg)
Generating autoload files
harley@olympic /m/i/b/w/i/Lychee ❯❯❯
```

### Output of the diagnostics (Settings => Diagnostics)
Inaccessible

### Browser and system

Palemoon (has always worked w/ previous installations. Also confirmed same result in Chrome)
Windows 10
Debian 9.6

```
harley@olympic /m/i/b/w/i/Lychee ❯❯❯ mysql lycheeIncorrigible -u lychee -p
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 55
Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [lycheeIncorrigible]> show tables;
+------------------------------+
| Tables_in_lycheeIncorrigible |
+------------------------------+
| lychee_albums                |
| lychee_log                   |
| lychee_photos                |
| lychee_settings              |
+------------------------------+
4 rows in set (0.00 sec)

MariaDB [lycheeIncorrigible]> SELECT * FROM lychee_settings WHERE `key` = "version";
+---------+--------+
| key     | value  |
+---------+--------+
| version | 030102 |
+---------+--------+
1 row in set (0.00 sec)
```

```
harley@olympic ~ ❯❯❯ php -m
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

```
harley@olympic ~ ❯❯❯ sudo aptitude search php|grep "^i"
i A libapache2-mod-php7.0 - server-side, HTML-embedded scripting language (Apache 2 module)
i  libapache2-mod-php7.1 - server-side, HTML-embedded scripting language (Apache 2 module)
i A libapache2-mod-php7.2 - server-side, HTML-embedded scripting language (Apache 2 module)
i  php - server-side, HTML-embedded scripting language (default)
i A php-auth-sasl - Abstraction of various SASL mechanism responses
i A php-cli-prompt - tiny helper prompting for user input
i A php-common - Common files for PHP packages
i A php-composer-ca-bundle - utility library to find a path to the system CA bundle
i A php-composer-semver - utilities, version constraint parsing and validation
i A php-composer-spdx-licenses - SPDX licenses list and validation library
i  php-gd - GD module for PHP [default]
i A php-igbinary - igbinary PHP serializer
i  php-imagick - Provides a wrapper to the ImageMagick library
i A php-json-schema - implementation of JSON schema
i  php-mail - Class that provides multiple interfaces for sending emails
i  php-mbstring - MBSTRING module for PHP [default]
i  php-memcached - memcached extension module for PHP, uses libmemcached
i A php-msgpack - PHP extension for interfacing with MessagePack
i  php-mysql - MySQL module for PHP [default]
i A php-net-smtp - PHP PEAR module implementing SMTP protocol
i A php-net-socket - Network Socket Interface
i A php-pear - PEAR Base System
i A php-psr-log - common interface for logging libraries
i  php-redis - PHP extension for interfacing with Redis
i A php-symfony-console - run tasks from the command line
i A php-symfony-filesystem - basic filesystem utilities
i A php-symfony-finder - find files and directories
i A php-symfony-polyfill-mbstring - Symfony polyfill for the Mbstring extension
i A php-symfony-process - execute commands in sub-processes
i  php-zip - Zip module for PHP [default]
i A php7.0-cli - command-line interpreter for the PHP scripting language
i A php7.0-common - documentation, examples and common module for PHP
i A php7.0-json - JSON module for PHP
i A php7.0-opcache - Zend OpCache module for PHP
i A php7.0-readline - readline module for PHP
i  php7.1 - server-side, HTML-embedded scripting language (metapackage)
i  php7.1-bz2 - bzip2 module for PHP
i  php7.1-cli - command-line interpreter for the PHP scripting language
i  php7.1-common - documentation, examples and common module for PHP
i  php7.1-curl - CURL module for PHP
i  php7.1-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
i  php7.1-gd - GD module for PHP
i  php7.1-json - JSON module for PHP
i  php7.1-mbstring - MBSTRING module for PHP
i  php7.1-mcrypt - libmcrypt module for PHP
i  php7.1-mysql - MySQL module for PHP
i A php7.1-opcache - Zend OpCache module for PHP
i A php7.1-readline - readline module for PHP
i  php7.1-sqlite3 - SQLite3 module for PHP
i  php7.1-sqlite3-dbgsym - debug symbols for php7.1-sqlite3
i  php7.1-tidy - tidy module for PHP
i  php7.1-xml - DOM, SimpleXML, WDDX, XML, and XSL module for PHP
i  php7.1-zip - Zip module for PHP
i A php7.2 - server-side, HTML-embedded scripting language (metapackage)
i A php7.2-cli - command-line interpreter for the PHP scripting language
i A php7.2-common - documentation, examples and common module for PHP
i A php7.2-gd - GD module for PHP
i A php7.2-json - JSON module for PHP
i A php7.2-mbstring - MBSTRING module for PHP
i A php7.2-mysql - MySQL module for PHP
i A php7.2-opcache - Zend OpCache module for PHP
i A php7.2-readline - readline module for PHP
i A php7.2-zip - Zip module for PHP
harley@olympic ~ ❯❯❯
```

```
harley@olympic ~ ❯❯❯ screenfetch
         _,met$$$$$gg.           harley@olympic
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 9.6 stretch
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.9.0-8-amd64
   ,$$P'              `$$$.      Uptime: 12h 6m
  ',$$P       ,ggs.     `$$b:    Packages: 2779
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.3.1
   $$P      d$'     ,    $$P     CPU: Intel Core i5-4590 CPU @ 3.298GHz
   $$:      $$.   -    ,d$$'     RAM: 777MiB / 3955MiB
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""

```

**Comment by ildyria** [comment]
This is very surprising. I'm going to dig this up.

**Comment by ildyria** [comment]
@Oozemeister can you make add the following two lines at the top of `php/index.php` after the `use`  :
```php
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 'On');  //On or Off
```
This should give you this:
```php
<?php

/**
 * @author    Tobias Reich
 * @copyright 2016 by Tobias Reich
 */

namespace Lychee;

use Lychee\Modules\Config;
use Lychee\Modules\Response;
use Lychee\Modules\Settings;
use Lychee\Modules\Validator;

use Lychee\Access\Installation;
use Lychee\Access\Admin;
use Lychee\Access\Guest;

ini_set('error_reporting', E_ALL);
ini_set('display_errors', 'On');  //On or Off
```

Hopefully this will give you some info instead of a white screen in the response panel.

**Comment by ghost** [comment]
Here's the Response under the Network tab when investigating index.php. Looks like I'm missing 'mysqli'...

```
<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Mysqli' not found in /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Database.php:85
Stack trace:
#0 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Database.php(57): Lychee\Modules\Database::connect('localhost', 'lychee', 'REDACTED_PASSWORD')
#1 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Database.php(35): Lychee\Modules\Database-&gt;__construct('localhost', 'lychee', 'REDACTED_PASSWORD', 'lycheeIncorr...', '')
#2 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Settings.php(17): Lychee\Modules\Database::get()
#3 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Plugins.php(21): Lychee\Modules\Settings::get()
#4 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Session.php(14): Lychee\Modules\Plugins::get()
#5 /media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Access/Guest.php(117): Lychee\Modules\Session-&gt;init(true)
#6 /media/iva in <b>/media/ivanka/backupLinux/websiteBackups/incorrigible/gallery/php/Modules/Database.php</b> on line <b>85</b><br />
```

So, I tried installing the php-mysql package, and it appears it is already installed. Unsure where to go from here.
```

harley@olympic` ~ ❯❯❯ sudo apt-get install php-mysqli
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php-mysqli is a virtual package provided by:
  php7.3-mysql 7.3.1-1+0~20190113101756.25+stretch~1.gbp15aaa9
  php7.2-mysql 7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69
  php7.1-mysql 7.1.26-1+0~20190113101810.12+stretch~1.gbp7077bb
  php7.0-mysql 7.0.33-1+0~20181208203126.8+stretch~1.gbp2ff763
  php5.6-mysql 5.6.40-1+0~20190111135530.9+stretch~1.gbp5f42c9
You should explicitly select one to install.

E: Package 'php-mysqli' has no installation candidate
harley@olympic ~ ❯❯❯ php --version                                                                                                                                                                                                                                      ✘ 100
PHP 7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69 (cli) (built: Jan 13 2019 10:07:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69, Copyright (c) 1999-2018, by Zend Technologies
harley@olympic ~ ❯❯❯ sudo apt-get install php7.2-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.2-mysql is already the newest version (7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by ildyria** [comment]
Can you create a file containing just that :
```php
<?php

phpinfo();
exit;
```
and access it ? This will allow you to check what is enabled or not. This functionality was usually provided with `index.php?fn=phpinfo` (once connected as an admin) but as you cannot even connect...

Also you might want to check that apache2 is indeed running php7.2 and not 7.0.
And you might want to restart your server `service apache2 restart`.
Sometimes it just solves things. :/

**Comment by ghost** [comment]
Turns out I was using php7.0 rather than 7.2. After making that change and the advised php.ini modifications suggested on the Installation page, my old data and db loaded successfully in the new LycheeOrg release.

However, I am still receiving strange "Server error or API not found" notifications when I access Settings in the left panel. Otherwise, the installation seems to operate normally, although I haven't yet tested all the Settings functions yet. I created another LycheeOrg instance to try to replicate this issue. 

I'm now able to actually generate a config.php file, unlike before. Tables are created in my empty database, but I only receive another "Server rror or API not found" notification at the top of my screen.
![palemoon_2019-01-20_10-11-49](https://user-images.githubusercontent.com/5841249/51441132-57801b00-1c9c-11e9-8f91-5705e4e168be.png)

Investigating the network reply, I see I'm receiving a 404 on a user.css file, which I can't even locate in the installation directory. I also receive a syntax error from the main.js file.
![palemoon_2019-01-20_10-13-53](https://user-images.githubusercontent.com/5841249/51441133-5949de80-1c9c-11e9-880d-8e65d7d9d9b7.png)

**Comment by ildyria** [comment]
> Turns out I was using php7.0 rather than 7.2. After making that change and the advised php.ini modifications suggested on the Installation page, my old data and db loaded successfully in the new LycheeOrg release.

Yay :+1: 

> However, I am still receiving strange "Server error or API not found" notifications when I access Settings in the left panel. Otherwise, the installation seems to operate normally, although I haven't yet tested all the Settings functions yet. I created another LycheeOrg instance to try to replicate this issue.

Nothing wrong, just you are missing the `user.css` If you click once on "Change CSS" it will disappear (as the file will be created).

> I also receive a syntax error from the main.js file.

There is no syntax error. It's just that it expected some text and it got the 404.html file of your server.
